name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev, test ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run tests
        run: |
          pytest tests/

  deploy-test:
    needs: test
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Test Environment
        run: |
          echo "Deploying to test environment"
          python scripts/switch_env.py dev

  deploy-dev:
    needs: test
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Development
        run: |
          echo "Deploying to development environment"
          python scripts/switch_env.py dev

  deploy-prod:
    needs: [test, deploy-test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://nifty-fifty-jse.replit.app
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deploying to production environment"
          python scripts/switch_env.py prod