[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false


[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
font = "sans serif"
